-- AlterTable
ALTER TABLE "Game" ADD COLUMN     "playedOn" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "createdOn" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP;
