-- AlterTable
ALTER TABLE "Game" ALTER COLUMN "wpm" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "accuracy" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "Statistic" ALTER COLUMN "bestAccuracy" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "averageAccuracy" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "averageWpm" SET DATA TYPE DECIMAL(65,30);
